# This includes all the same stuff as default_config_extragalactic.yaml,
#   but then adds stuff that might modify things for the galaxy.

overrides:
  - pipeline_config.yaml
  - pipeline_config_galactic.yaml
  - site_config.yaml
  - site_config_galactic.yaml
  - alert_config.yaml
  - alert_config_galactic.yaml
  - default_local_overrides.yaml
  - default_local_overrides_galactic.yaml


configchoice:
  choice_algorithm: null
