"""object_legacy_survey_match

Revision ID: 7bc901895107
Revises: 5daf04627101
Create Date: 2025-07-30 17:02:40.438759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc901895107'
down_revision = '5daf04627101'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_legacy_survey_match',
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('lsid', sa.BigInteger(), nullable=False),
    sa.Column('ra', sa.Double(), nullable=False),
    sa.Column('dec', sa.Double(), nullable=False),
    sa.Column('dist', sa.Double(), nullable=False),
    sa.Column('white_mag', sa.Double(), nullable=False),
    sa.Column('xgboost', sa.REAL(), nullable=False),
    sa.Column('is_star', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects._id'], name='object_ls_match_object_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_object_legacy_survey_match__id'), 'object_legacy_survey_match', ['_id'], unique=False)
    op.create_index(op.f('ix_object_legacy_survey_match_created_at'), 'object_legacy_survey_match', ['created_at'], unique=False)
    op.create_index(op.f('ix_object_legacy_survey_match_object_id'), 'object_legacy_survey_match', ['object_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_object_legacy_survey_match_object_id'), table_name='object_legacy_survey_match')
    op.drop_index(op.f('ix_object_legacy_survey_match_created_at'), table_name='object_legacy_survey_match')
    op.drop_index(op.f('ix_object_legacy_survey_match__id'), table_name='object_legacy_survey_match')
    op.drop_table('object_legacy_survey_match')
    # ### end Alembic commands ###
