"""knownexposure_state

Revision ID: b5c481ead8af
Revises: ddb3f80c9bfb
Create Date: 2025-07-01 14:19:59.615487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c481ead8af'
down_revision = 'ddb3f80c9bfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knownexposures', sa.Column('_state', sa.SMALLINT(), server_default='0', nullable=False))
    op.drop_column('knownexposures', 'hold')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knownexposures', sa.Column('hold', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('knownexposures', '_state')
    # ### end Alembic commands ###
