"""wcs_four_corners

Revision ID: f8eeea7c3e96
Revises: f83cba8ee519
Create Date: 2026-06-08 18:22:59.617683

"""
import textwrap
import time

from psycopg import sql
from alembic import op
import sqlalchemy as sa

from models.base import PGDB, FourCorners
from models.image import Image
from models.world_coordinates import WorldCoordinates

from util.logger import SCLogger

# revision identifiers, used by Alembic.
revision = 'f8eeea7c3e96'
down_revision = 'f83cba8ee519'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_excerpts_dec_corner_00'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_dec_corner_01'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_dec_corner_10'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_dec_corner_11'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_ra_corner_00'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_ra_corner_01'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_ra_corner_10'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_ra_corner_11'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_images_dec_corner_00'), table_name='images')
    op.drop_index(op.f('ix_images_dec_corner_01'), table_name='images')
    op.drop_index(op.f('ix_images_dec_corner_10'), table_name='images')
    op.drop_index(op.f('ix_images_dec_corner_11'), table_name='images')
    op.drop_index(op.f('ix_images_ra_corner_00'), table_name='images')
    op.drop_index(op.f('ix_images_ra_corner_01'), table_name='images')
    op.drop_index(op.f('ix_images_ra_corner_10'), table_name='images')
    op.drop_index(op.f('ix_images_ra_corner_11'), table_name='images')
    op.add_column('world_coordinates', sa.Column('ra', sa.Double()))
    op.add_column('world_coordinates', sa.Column('dec', sa.Double()))
    op.add_column('world_coordinates', sa.Column('gallat', sa.Double(), nullable=True))
    op.add_column('world_coordinates', sa.Column('gallon', sa.Double(), nullable=True))
    op.add_column('world_coordinates', sa.Column('ecllat', sa.Double(), nullable=True))
    op.add_column('world_coordinates', sa.Column('ecllon', sa.Double(), nullable=True))
    op.add_column('world_coordinates', sa.Column('ra_good_00', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('ra_good_01', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('ra_good_10', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('ra_good_11', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('dec_good_00', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('dec_good_01', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('dec_good_10', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('dec_good_11', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('good_minra', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('good_maxra', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('good_mindec', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('good_maxdec', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('ra_corner_00', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('ra_corner_01', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('ra_corner_10', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('ra_corner_11', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('dec_corner_00', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('dec_corner_01', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('dec_corner_10', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('dec_corner_11', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('minra', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('maxra', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('mindec', sa.REAL()))
    op.add_column('world_coordinates', sa.Column('maxdec', sa.REAL()))
    op.create_index(op.f('ix_world_coordinates_ecllat'), 'world_coordinates', ['ecllat'], unique=False)
    op.create_index(op.f('ix_world_coordinates_gallat'), 'world_coordinates', ['gallat'], unique=False)
    op.create_index(op.f('ix_world_coordinates_good_maxdec'), 'world_coordinates', ['good_maxdec'], unique=False)
    op.create_index(op.f('ix_world_coordinates_good_maxra'), 'world_coordinates', ['good_maxra'], unique=False)
    op.create_index(op.f('ix_world_coordinates_good_mindec'), 'world_coordinates', ['good_mindec'], unique=False)
    op.create_index(op.f('ix_world_coordinates_good_minra'), 'world_coordinates', ['good_minra'], unique=False)
    op.create_index(op.f('ix_world_coordinates_maxdec'), 'world_coordinates', ['maxdec'], unique=False)
    op.create_index(op.f('ix_world_coordinates_maxra'), 'world_coordinates', ['maxra'], unique=False)
    op.create_index(op.f('ix_world_coordinates_mindec'), 'world_coordinates', ['mindec'], unique=False)
    op.create_index(op.f('ix_world_coordinates_minra'), 'world_coordinates', ['minra'], unique=False)
    op.create_index('world_coordinates_q3c_ang2ipix_idx', 'world_coordinates', [sa.literal_column('q3c_ang2ipix(ra, dec)')], unique=False)
    # ### end Alembic commands ###

    # Run all existing WCSes to get the corners and the good corners
    with PGDB( op.get_bind().connection.driver_connection, dictcursor=True ) as pgdb:
        rows = pgdb.execute( "SELECT w._id AS wcsid,i._id AS imgid "
                             "FROM world_coordinates w "
                             "INNER JOIN source_lists s ON w.sources_id=s._id "
                             "INNER JOIN images i ON s.image_id=i._id "
                             "ORDER BY i.created_at DESC" )

        SCLogger.warning( f"Have to update {len(rows)} wcs rows." )
        pgdb.echoqueries = False

        times = { 'getimg': 0.,
                  'getflags': 0.,
                  'getwcs': 0.,
                  'setcorners': 0.,
                  'update': 0 }
        for ndid, row in enumerate(rows):
            if ( ndid > 0 ) and ( ndid % 50 == 0):
                nlsp = '\n        '
                SCLogger.warning( f"...did {ndid} of {len(rows)}\n"
                                  f"{nlsp.join(f'{k:>10s}: {v:.3f}' for k, v in times.items())}" )
                break
            t0 = time.perf_counter()
            img = Image.get_by_id( row['imgid'], pgdb )
            t1 = time.perf_counter()
            mask = img.flags
            t2 = time.perf_counter()
            wcs = WorldCoordinates.get_by_id( row['wcsid'], pgdb )
            t3 = time.perf_counter()
            
            wcs.set_corners_from_wcs( wcs.wcs, setradec=True, mask=mask )
            t4 =time.perf_counter()
            
            q = sql.SQL( textwrap.dedent(
                """\
                UPDATE world_coordinates
                SET ra={ra},
                    dec={dec},
                    gallat={gallat},
                    gallon={gallon},
                    ecllat={ecllat},
                    ecllon={ecllon},
                    ra_corner_00={ra00},
                    ra_corner_01={ra01},
                    ra_corner_10={ra10},
                    ra_corner_11={ra11},
                    dec_corner_00={dec00},
                    dec_corner_01={dec01},
                    dec_corner_10={dec10},
                    dec_corner_11={dec11},
                    minra={minra},
                    maxra={maxra},
                    mindec={mindec},
                    maxdec={maxdec},
                    ra_good_00={ragood00},
                    ra_good_01={ragood01},
                    ra_good_10={ragood10},
                    ra_good_11={ragood11},
                    dec_good_00={decgood00},
                    dec_good_01={decgood01},
                    dec_good_10={decgood10},
                    dec_good_11={decgood11},
                    good_minra={good_minra},
                    good_maxra={good_maxra},
                    good_mindec={good_mindec},
                    good_maxdec={good_maxdec}
                WHERE _id={id}
                """
            ) ).format( ra=wcs.ra,
                        dec=wcs.dec,
                        gallat=wcs.gallat,
                        gallon=wcs.gallon,
                        ecllat=wcs.ecllat,
                        ecllon=wcs.ecllon,
                        ra00=wcs.ra_corner_00,
                        ra01=wcs.ra_corner_01,
                        ra10=wcs.ra_corner_10,
                        ra11=wcs.ra_corner_11,
                        dec00=wcs.dec_corner_00,
                        dec01=wcs.dec_corner_01,
                        dec10=wcs.dec_corner_10,
                        dec11=wcs.dec_corner_11,
                        minra=wcs.minra,
                        maxra=wcs.maxra,
                        mindec=wcs.mindec,
                        maxdec=wcs.maxdec,
                        ragood00=wcs.ra_good_00,
                        ragood01=wcs.ra_good_01,
                        ragood10=wcs.ra_good_10,
                        ragood11=wcs.ra_good_11,
                        decgood00=wcs.dec_good_00,
                        decgood01=wcs.dec_good_01,
                        decgood10=wcs.dec_good_10,
                        decgood11=wcs.dec_good_11,
                        good_minra=wcs.good_minra,
                        good_maxra=wcs.good_maxra,
                        good_mindec=wcs.good_mindec,
                        good_maxdec=wcs.good_maxdec,
                        id=wcs._id )

            pgdb.execute_nofetch( q )
            t5 = time.perf_counter()
            times['getimg'] += t1 - t0
            times['getflags'] += t2 - t1
            times['getwcs'] += t3 - t2
            times['setcorners'] += t4 - t3
            times['update'] += t5 - t4

    # I had to remove the "nullable=False" from the column creation above; now
    #   that they're filled, put them back in.

    import pdb; pdb.set_trace()
    SCLogger.warning( "Done updating columns, making lots of fields non-nullable" )
    
    for col in [ 'ra', 'dec',
                 'ra_good_00', 'ra_good_01', 'ra_good_10', 'ra_good_11',
                 'dec_good_00', 'dec_good_01', 'dec_good_10', 'dec_good_11',
                 'good_minra', 'good_maxra', 'good_mindec', 'good_maxdec',
                 'ra_corner_00', 'ra_corner_01', 'ra_corner_10', 'ra_corner_11',
                 'dec_corner_00', 'dec_corner_01', 'dec_corner_10', 'dec_corner_11',
                 'minra', 'maxra', 'mindec', 'maxdec' ]:
        op.alter_column( 'world_coordinates', col, nullable=False )
            
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('world_coordinates_q3c_ang2ipix_idx', table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates_minra'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates_mindec'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates_maxra'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates_maxdec'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates_good_minra'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates_good_mindec'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates_good_maxra'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates_good_maxdec'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates_gallat'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates_ecllat'), table_name='world_coordinates')
    op.drop_column('world_coordinates', 'maxdec')
    op.drop_column('world_coordinates', 'mindec')
    op.drop_column('world_coordinates', 'maxra')
    op.drop_column('world_coordinates', 'minra')
    op.drop_column('world_coordinates', 'dec_corner_11')
    op.drop_column('world_coordinates', 'dec_corner_10')
    op.drop_column('world_coordinates', 'dec_corner_01')
    op.drop_column('world_coordinates', 'dec_corner_00')
    op.drop_column('world_coordinates', 'ra_corner_11')
    op.drop_column('world_coordinates', 'ra_corner_10')
    op.drop_column('world_coordinates', 'ra_corner_01')
    op.drop_column('world_coordinates', 'ra_corner_00')
    op.drop_column('world_coordinates', 'good_maxdec')
    op.drop_column('world_coordinates', 'good_mindec')
    op.drop_column('world_coordinates', 'good_maxra')
    op.drop_column('world_coordinates', 'good_minra')
    op.drop_column('world_coordinates', 'dec_good_11')
    op.drop_column('world_coordinates', 'dec_good_10')
    op.drop_column('world_coordinates', 'dec_good_01')
    op.drop_column('world_coordinates', 'dec_good_00')
    op.drop_column('world_coordinates', 'ra_good_11')
    op.drop_column('world_coordinates', 'ra_good_10')
    op.drop_column('world_coordinates', 'ra_good_01')
    op.drop_column('world_coordinates', 'ra_good_00')
    op.drop_column('world_coordinates', 'ecllon')
    op.drop_column('world_coordinates', 'ecllat')
    op.drop_column('world_coordinates', 'gallon')
    op.drop_column('world_coordinates', 'gallat')
    op.drop_column('world_coordinates', 'dec')
    op.drop_column('world_coordinates', 'ra')
    op.create_index(op.f('ix_images_ra_corner_11'), 'images', ['ra_corner_11'], unique=False)
    op.create_index(op.f('ix_images_ra_corner_10'), 'images', ['ra_corner_10'], unique=False)
    op.create_index(op.f('ix_images_ra_corner_01'), 'images', ['ra_corner_01'], unique=False)
    op.create_index(op.f('ix_images_ra_corner_00'), 'images', ['ra_corner_00'], unique=False)
    op.create_index(op.f('ix_images_dec_corner_11'), 'images', ['dec_corner_11'], unique=False)
    op.create_index(op.f('ix_images_dec_corner_10'), 'images', ['dec_corner_10'], unique=False)
    op.create_index(op.f('ix_images_dec_corner_01'), 'images', ['dec_corner_01'], unique=False)
    op.create_index(op.f('ix_images_dec_corner_00'), 'images', ['dec_corner_00'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_ra_corner_11'), 'catalog_excerpts', ['ra_corner_11'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_ra_corner_10'), 'catalog_excerpts', ['ra_corner_10'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_ra_corner_01'), 'catalog_excerpts', ['ra_corner_01'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_ra_corner_00'), 'catalog_excerpts', ['ra_corner_00'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_dec_corner_11'), 'catalog_excerpts', ['dec_corner_11'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_dec_corner_10'), 'catalog_excerpts', ['dec_corner_10'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_dec_corner_01'), 'catalog_excerpts', ['dec_corner_01'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_dec_corner_00'), 'catalog_excerpts', ['dec_corner_00'], unique=False)
    # ### end Alembic commands ###
