"""gaia_downloadlock_intnotfloat

Revision ID: f83cba8ee519
Revises: 43c53217262d
Create Date: 2026-06-03 19:26:14.311617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83cba8ee519'
down_revision = '43c53217262d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gaiadr3_downloadlock', 'minra',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('gaiadr3_downloadlock', 'maxra',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('gaiadr3_downloadlock', 'mindec',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('gaiadr3_downloadlock', 'maxdec',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('gaiadr3_downloadlock', 'minmag',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('gaiadr3_downloadlock', 'maxmag',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gaiadr3_downloadlock', 'maxmag',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('gaiadr3_downloadlock', 'minmag',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('gaiadr3_downloadlock', 'maxdec',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('gaiadr3_downloadlock', 'mindec',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('gaiadr3_downloadlock', 'maxra',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('gaiadr3_downloadlock', 'minra',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
