"""image_unique

Revision ID: 3895e6b8b255
Revises: d3a2c0ab248e
Create Date: 2026-09-01 15:09:31.465571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3895e6b8b255'
down_revision = 'd3a2c0ab248e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_image_provexpsec_uniq', 'images', ['provenance_id', 'exposure_id', 'section_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_image_provexpsec_uniq', 'images', type_='unique')
    # ### end Alembic commands ###
