"""warp_parent

Revision ID: 0687ed5e7eed
Revises: 04d912266c55
Create Date: 2026-09-13 18:10:48.924476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0687ed5e7eed'
down_revision = '04d912266c55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_warp_parent',
    sa.Column('warped_id', sa.UUID(), nullable=False),
    sa.Column('unwarped_zp_id', sa.UUID(), nullable=False),
    sa.Column('target_wcs_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['target_wcs_id'], ['world_coordinates._id'], name='image_warped_target_wcs_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unwarped_zp_id'], ['zero_points._id'], name='image_warped_unwarped_zp_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warped_id'], ['images._id'], name='image_warped_image_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('warped_id')
    )
    op.create_index(op.f('ix_image_warp_parent_target_wcs_id'), 'image_warp_parent', ['target_wcs_id'], unique=False)
    op.create_index(op.f('ix_image_warp_parent_unwarped_zp_id'), 'image_warp_parent', ['unwarped_zp_id'], unique=False)
    op.create_index(op.f('ix_image_warp_parent_warped_id'), 'image_warp_parent', ['warped_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_warp_parent_warped_id'), table_name='image_warp_parent')
    op.drop_index(op.f('ix_image_warp_parent_unwarped_zp_id'), table_name='image_warp_parent')
    op.drop_index(op.f('ix_image_warp_parent_target_wcs_id'), table_name='image_warp_parent')
    op.drop_table('image_warp_parent')
    # ### end Alembic commands ###
