"""object_is_bad_default_false

Revision ID: 01874a39a906
Revises: 979a63537d73
Create Date: 2026-09-10 13:35:28.431362

"""
from alembic import op
from models.base import PGDB


# revision identifiers, used by Alembic.
revision = '01874a39a906'
down_revision = '979a63537d73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    #... wow, that was helpful, Alembic
    with PGDB( op.get_bind().connection.driver_connection ) as pgdb:
        pgdb.execute( "ALTER TABLE objects ALTER COLUMN is_bad SET DEFAULT FALSE" )
        pgdb.commit()

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    with PGDB( op.get_bind().connection.driver_connection ) as pgdb:
        pgdb.execute( "ALTER TABLE objects ALTER COLUMN is_bad DROP DEFAULT" )
        pgdb.commit()
