"""wcs_sources_id_notunique

Revision ID: 43c53217262d
Revises: 53c8dfd09cca
Create Date: 2026-06-02 18:39:06.291967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c53217262d'
down_revision = '53c8dfd09cca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_world_coordinates_sources_id'), table_name='world_coordinates')
    op.create_index(op.f('ix_world_coordinates_sources_id'), 'world_coordinates', ['sources_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_world_coordinates_sources_id'), table_name='world_coordinates')
    op.create_index(op.f('ix_world_coordinates_sources_id'), 'world_coordinates', ['sources_id'], unique=True)
    # ### end Alembic commands ###
