"""ref_validity_dates

Revision ID: 2be1834e8869
Revises: f8eeea7c3e96
Create Date: 2026-06-12 18:29:40.503199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be1834e8869'
down_revision = 'f8eeea7c3e96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refs', sa.Column('validity_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('refs', sa.Column('validity_end', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_refs_validity_end'), 'refs', ['validity_end'], unique=False)
    op.create_index(op.f('ix_refs_validity_start'), 'refs', ['validity_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refs_validity_start'), table_name='refs')
    op.drop_index(op.f('ix_refs_validity_end'), table_name='refs')
    op.drop_column('refs', 'validity_end')
    op.drop_column('refs', 'validity_start')
    # ### end Alembic commands ###
