"""x_y_on_diaforcedphot

Revision ID: f6577efe80e0
Revises: 7fa716df8721
Create Date: 2026-10-09 15:03:54.647699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6577efe80e0'
down_revision = '7fa716df8721'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dia_forced_photometry', sa.Column('x', sa.REAL(), server_default=sa.text("'NaN'"), nullable=False))
    op.add_column('dia_forced_photometry', sa.Column('y', sa.REAL(), server_default=sa.text("'NaN'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dia_forced_photometry', 'y')
    op.drop_column('dia_forced_photometry', 'x')
    # ### end Alembic commands ###
