"""image width/height

Revision ID: d3a2c0ab248e
Revises: 2be1834e8869
Create Date: 2026-08-27 21:10:25.748220

"""
from alembic import op
import sqlalchemy as sa

from psycopg import sql
from astropy.io import fits

from models.base import PGDB
from models.image import Image

# revision identifiers, used by Alembic.
revision = 'd3a2c0ab248e'
down_revision = '2be1834e8869'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('images', sa.Column('width', sa.SmallInteger(), nullable=True))
    op.add_column('images', sa.Column('height', sa.SmallInteger(), nullable=True))

    # OK, this is going to be totally slow, because every image will need to be opened!
    with PGDB( op.get_bind().connection.driver_connection, dictcursor=True ) as pgdb:
        rows = pgdb.execute( "SELECT _id FROM images" )
        for row in rows:
            imageid = row['_id']
            image = Image.get_by_id( imageid )
            pgdb.execute( sql.SQL( "UPDATE images SET width={wid}, height={hei} WHERE _id={imid}" )
                          .format( wid=image.data.shape[1], hei=image.data.shape[0], imid=imageid ) )

    op.alter_column( "images", "width", nullable=False )
    op.alter_column( "images", "height", nullable=False )
    
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'height')
    op.drop_column('images', 'width')
    # ### end Alembic commands ###
