"""forcedphot_to_diaforcedphot

Revision ID: 7fa716df8721
Revises: 0687ed5e7eed
Create Date: 2026-10-09 13:33:41.324432

"""
from alembic import op
import sqlalchemy as sa

from models.base import PGDB

# revision identifiers, used by Alembic.
revision = '7fa716df8721'
down_revision = '0687ed5e7eed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_warp_parent', sa.Column('warp_provenance_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_image_warp_parent_warp_provenance_id'), 'image_warp_parent', ['warp_provenance_id'], unique=False)
    op.create_unique_constraint('warp_unique', 'image_warp_parent', ['unwarped_zp_id', 'target_wcs_id', 'warp_provenance_id'])
    op.create_foreign_key('image_warped_prov_fkey', 'image_warp_parent', 'provenances', ['warp_provenance_id'], ['_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###

    # Doing this manually because it would take me a lot longer to make
    # sure I got the order of operations right trying to do this with
    # SQLAlchemy and alembic.  (Yet ONE MORE way I regret ever having heard
    # about SQLAlchemy in the first place.)
    
    with PGDB( op.get_bind().connection.driver_connection ) as pgdb:
        pgdb.execute( "ALTER TABLE forced_photometry RENAME CONSTRAINT forced_photometry_pkey "
                      "TO dia_forced_photometry_pkey" )
        pgdb.execute( "ALTER TABLE forced_photometry RENAME CONSTRAINT forcedphot_unique "
                      "TO dia_forcedphot_unique" )
        pgdb.execute( "ALTER TABLE forced_photometry RENAME CONSTRAINT forcedphot_object_id_fkey "
                      "TO dia_forcedphot_object_id_fkey" )
        pgdb.execute( "ALTER TABLE forced_photometry RENAME CONSTRAINT forcedphot_object_position_id_fkey "
                      "TO dia_forcedphot_object_position_id_fkey" )
        pgdb.execute( "ALTER TABLE forced_photometry RENAME CONSTRAINT forcedphot_provenance_id_fkey "
                      "TO dia_forcedphot_provenance_id_fkey" )
        pgdb.execute( "ALTER TABLE forced_photometry RENAME CONSTRAINT forcedphot_subtraction_id_fkey "
                      "TO dia_forcedphot_subtraction_id_fkey" )
        pgdb.execute( "ALTER TABLE forced_photometry RENAME TO dia_forced_photometry" )
        pgdb.execute( "ALTER INDEX ix_forced_photometry__bitflag RENAME TO ix_dia_forced_photometry__bitflag" )
        pgdb.execute( "ALTER INDEX ix_forced_photometry__id RENAME TO ix_dia_forced_photometry__id" )
        pgdb.execute( "ALTER INDEX ix_forced_photometry__upstream_bitflag "
                      "RENAME TO ix_dia_forced_photometry__upstream_bitflag" )
        pgdb.execute( "ALTER INDEX ix_forced_photometry_created_at RENAME TO ix_dia_forced_photometry_created_at" )
        pgdb.execute( "ALTER INDEX ix_forced_photometry_object_id RENAME TO ix_dia_forced_photometry_object_id" )
        pgdb.execute( "ALTER INDEX ix_forced_photometry_object_position_id "
                      "RENAME TO ix_dia_forced_photometry_object_position_id" )
        pgdb.execute( "ALTER INDEX ix_forced_photometry_provenance_id RENAME TO ix_dia_forced_photometry_provenance_id" )
        pgdb.execute( "ALTER INDEX ix_forced_photometry_subtraction_id "
                      "RENAME TO ix_dia_forced_photometry_subtraction_id" )
        

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_warped_prov_fkey', 'image_warp_parent', type_='foreignkey')
    op.drop_constraint('warp_unique', 'image_warp_parent', type_='unique')
    op.drop_index(op.f('ix_image_warp_parent_warp_provenance_id'), table_name='image_warp_parent')
    op.drop_column('image_warp_parent', 'warp_provenance_id')
    # ### end Alembic commands ###

    with PGDB( op.get_bind().connection.driver_connection ) as pgdb:
        pgdb.execute( "ALTER INDEX ix_dia_forced_photometry__bitflag RENAME TO ix_forced_photometry__bitflag" )
        pgdb.execute( "ALTER INDEX ix_dia_forced_photometry__id RENAME TO ix_forced_photometry__id" )
        pgdb.execute( "ALTER INDEX ix_dia_forced_photometry__upstream_bitflag "
                      "RENAME TO ix_forced_photometry__upstream_bitflag" )
        pgdb.execute( "ALTER INDEX ix_dia_forced_photometry_created_at RENAME TO ix_forced_photometry_created_at" )
        pgdb.execute( "ALTER INDEX ix_dia_forced_photometry_object_id RENAME TO ix_forced_photometry_object_id" )
        pgdb.execute( "ALTER INDEX ix_dia_forced_photometry_object_position_id "
                      "RENAME TO ix_forced_photometry_object_position_id" )
        pgdb.execute( "ALTER INDEX ix_dia_forced_photometry_provenance_id RENAME TO ix_forced_photometry_provenance_id" )
        pgdb.execute( "ALTER INDEX ix_dia_forced_photometry_subtraction_id "
                      "RENAME TO ix_forced_photometry_subtraction_id" )
        pgdb.execute( "ALTER TABLE dia_forced_photometry RENAME TO forced_photometry" )
        pgdb.execute( "ALTER TABLE forced_photometry RENAME CONSTRAINT dia_forced_photometry_pkey "
                      "TO forced_photometry_pkey" )
        pgdb.execute( "ALTER TABLE forced_photometry RENAME CONSTRAINT dia_forcedphot_unique "
                      "TO forcedphot_unique" )
        pgdb.execute( "ALTER TABLE forced_photometry RENAME CONSTRAINT dia_forcedphot_object_id_fkey "
                      "TO forcedphot_object_id_fkey" )
        pgdb.execute( "ALTER TABLE forced_photometry RENAME CONSTRAINT dia_forcedphot_object_position_id_fkey "
                      "TO forcedphot_object_position_id_fkey" )
        pgdb.execute( "ALTER TABLE forced_photometry RENAME CONSTRAINT forcedphot_provenance_id_fkey "
                      "TO forcedphot_provenance_id_fkey" )
        pgdb.execute( "ALTER TABLE forced_photometry RENAME CONSTRAINT dia_forcedphot_subtraction_id_fkey "
                      "TO forcedphot_subtraction_id_fkey" )
    
