"""type_in_knownexposures

Revision ID: e6cae41b2dec
Revises: 968beeeda621
Create Date: 2026-05-14 15:56:04.097647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6cae41b2dec'
down_revision = '968beeeda621'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knownexposures', sa.Column('_type', sa.SMALLINT(), server_default=sa.text('0'), nullable=False))
    op.create_index(op.f('ix_knownexposures__type'), 'knownexposures', ['_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knownexposures__type'), table_name='knownexposures')
    op.drop_column('knownexposures', '_type')
    # ### end Alembic commands ###
