"""catalog_match_update

Revision ID: 4a9ea8d45b5c
Revises: 7bc901895107
Create Date: 2026-01-28 20:04:11.468926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9ea8d45b5c'
down_revision = '7bc901895107'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_gaia_match',
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('match_radius', sa.Integer(), nullable=False),
    sa.Column('gaia_sourceid', sa.BigInteger(), nullable=True),
    sa.Column('dist', sa.Double(), nullable=True),
    sa.Column('gaia_starprob', sa.REAL(), nullable=True),
    sa.Column('gaia_quasarprob', sa.REAL(), nullable=True),
    sa.Column('gaia_galaxyprob', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects._id'], name='object_gaia_match_object_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_id', 'match_radius', 'gaia_sourceid')
    )
    op.create_index('ix_gaia_match_objidmatchr', 'object_gaia_match', ['object_id', 'match_radius'], unique=False)
    op.create_index(op.f('ix_object_gaia_match_created_at'), 'object_gaia_match', ['created_at'], unique=False)
    op.create_index(op.f('ix_object_gaia_match_object_id'), 'object_gaia_match', ['object_id'], unique=False)
    op.add_column('object_legacy_survey_match', sa.Column('match_radius', sa.Integer(), nullable=False))
    op.alter_column('object_legacy_survey_match', 'lsid',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('object_legacy_survey_match', 'ra',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('object_legacy_survey_match', 'dec',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('object_legacy_survey_match', 'dist',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('object_legacy_survey_match', 'white_mag',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('object_legacy_survey_match', 'xgboost',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('object_legacy_survey_match', 'is_star',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_object_legacy_survey_match__id'), table_name='object_legacy_survey_match')
    op.create_index('ix_object_legacy_survey_match_objidmatchr', 'object_legacy_survey_match', ['object_id', 'match_radius'], unique=False)
    op.drop_column('object_legacy_survey_match', '_id')
    # ### end Alembic commands ###

    # Manually added by rknop -- alembic didn't detect this
    # NOTE : this does mean that there will be no primary key on _id when
    #   we downgrade, but oh well, I don't care that much.  Downgrade schmowngrade.
    op.create_primary_key( 'object_legacy_survey_match_pkey', 'object_legacy_survey_match',
                           [ 'object_id', 'match_radius', 'lsid' ] )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_legacy_survey_match', sa.Column('_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index('ix_object_legacy_survey_match_objidmatchr', table_name='object_legacy_survey_match')
    op.create_index(op.f('ix_object_legacy_survey_match__id'), 'object_legacy_survey_match', ['_id'], unique=False)
    op.alter_column('object_legacy_survey_match', 'is_star',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('object_legacy_survey_match', 'xgboost',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('object_legacy_survey_match', 'white_mag',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('object_legacy_survey_match', 'dist',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('object_legacy_survey_match', 'dec',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('object_legacy_survey_match', 'ra',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('object_legacy_survey_match', 'lsid',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('object_legacy_survey_match', 'match_radius')
    op.drop_index(op.f('ix_object_gaia_match_object_id'), table_name='object_gaia_match')
    op.drop_index(op.f('ix_object_gaia_match_created_at'), table_name='object_gaia_match')
    op.drop_index('ix_gaia_match_objidmatchr', table_name='object_gaia_match')
    op.drop_table('object_gaia_match')
    # ### end Alembic commands ###
