"""forced_phot

Revision ID: 979a63537d73
Revises: 3895e6b8b255
Create Date: 2026-09-09 18:02:32.051314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '979a63537d73'
down_revision = '3895e6b8b255'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forced_photometry',
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('object_position_id', sa.UUID(), nullable=True),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('subtraction_id', sa.UUID(), nullable=False),
    sa.Column('flux_psf', sa.REAL(), nullable=False),
    sa.Column('flux_psf_err', sa.REAL(), nullable=False),
    sa.Column('flux_apertures', postgresql.ARRAY(sa.REAL(), zero_indexes=True), nullable=False),
    sa.Column('flux_apertures_err', postgresql.ARRAY(sa.REAL(), zero_indexes=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('_upstream_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['objects._id'], name='forcedphot_object_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['object_position_id'], ['object_positions._id'], name='forcedphot_object_position_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='forcedphot_provenance_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtraction_id'], ['images._id'], name='forcedphot_subtraction_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('object_id', 'subtraction_id', 'provenance_id', name='forcedphot_unique')
    )
    op.create_index(op.f('ix_forced_photometry__bitflag'), 'forced_photometry', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_forced_photometry__id'), 'forced_photometry', ['_id'], unique=False)
    op.create_index(op.f('ix_forced_photometry__upstream_bitflag'), 'forced_photometry', ['_upstream_bitflag'], unique=False)
    op.create_index(op.f('ix_forced_photometry_created_at'), 'forced_photometry', ['created_at'], unique=False)
    op.create_index(op.f('ix_forced_photometry_object_id'), 'forced_photometry', ['object_id'], unique=False)
    op.create_index(op.f('ix_forced_photometry_object_position_id'), 'forced_photometry', ['object_position_id'], unique=False)
    op.create_index(op.f('ix_forced_photometry_provenance_id'), 'forced_photometry', ['provenance_id'], unique=False)
    op.create_index(op.f('ix_forced_photometry_subtraction_id'), 'forced_photometry', ['subtraction_id'], unique=False)
    op.create_table('image_trim_parent',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('trim_xcen', sa.SmallInteger(), nullable=False),
    sa.Column('trim_ycen', sa.SmallInteger(), nullable=False),
    sa.Column('parent_image_id', sa.UUID(), nullable=False),
    sa.Column('parent_wcs_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images._id'], name='image_trim_image_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_image_id'], ['images._id'], name='image_trim_parent_image_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_wcs_id'], ['world_coordinates._id'], name='image_trim_parent_wcs_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_image_trim_parent_image_id'), 'image_trim_parent', ['image_id'], unique=False)
    op.create_index(op.f('ix_image_trim_parent_parent_image_id'), 'image_trim_parent', ['parent_image_id'], unique=False)
    op.create_index(op.f('ix_image_trim_parent_parent_wcs_id'), 'image_trim_parent', ['parent_wcs_id'], unique=False)
    op.add_column('psfs', sa.Column('offset_x', sa.SMALLINT(), nullable=True))
    op.add_column('psfs', sa.Column('offset_y', sa.SMALLINT(), nullable=True))
    op.add_column('psfs', sa.Column('trimmed_width', sa.SMALLINT(), nullable=True))
    op.add_column('psfs', sa.Column('trimmed_height', sa.SMALLINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psfs', 'trimmed_height')
    op.drop_column('psfs', 'trimmed_width')
    op.drop_column('psfs', 'offset_y')
    op.drop_column('psfs', 'offset_x')
    op.drop_index(op.f('ix_image_trim_parent_parent_wcs_id'), table_name='image_trim_parent')
    op.drop_index(op.f('ix_image_trim_parent_parent_image_id'), table_name='image_trim_parent')
    op.drop_index(op.f('ix_image_trim_parent_image_id'), table_name='image_trim_parent')
    op.drop_table('image_trim_parent')
    op.drop_index(op.f('ix_forced_photometry_subtraction_id'), table_name='forced_photometry')
    op.drop_index(op.f('ix_forced_photometry_provenance_id'), table_name='forced_photometry')
    op.drop_index(op.f('ix_forced_photometry_object_position_id'), table_name='forced_photometry')
    op.drop_index(op.f('ix_forced_photometry_object_id'), table_name='forced_photometry')
    op.drop_index(op.f('ix_forced_photometry_created_at'), table_name='forced_photometry')
    op.drop_index(op.f('ix_forced_photometry__upstream_bitflag'), table_name='forced_photometry')
    op.drop_index(op.f('ix_forced_photometry__id'), table_name='forced_photometry')
    op.drop_index(op.f('ix_forced_photometry__bitflag'), table_name='forced_photometry')
    op.drop_table('forced_photometry')
    # ### end Alembic commands ###
