"""no_object_match_tables

Revision ID: 968beeeda621
Revises: 4a9ea8d45b5c
Create Date: 2026-01-29 20:19:03.016794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968beeeda621'
down_revision = '4a9ea8d45b5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('no_object_gaia_matches',
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('match_radius', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects._id'], name='no_object_gaia_match_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_id', 'match_radius')
    )
    op.create_index(op.f('ix_no_object_gaia_matches_created_at'), 'no_object_gaia_matches', ['created_at'], unique=False)
    op.create_index(op.f('ix_no_object_gaia_matches_object_id'), 'no_object_gaia_matches', ['object_id'], unique=False)
    op.create_table('no_object_legacy_survey_matches',
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('match_radius', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects._id'], name='no_object_legacy_survey_match_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_id', 'match_radius')
    )
    op.create_index(op.f('ix_no_object_legacy_survey_matches_created_at'), 'no_object_legacy_survey_matches', ['created_at'], unique=False)
    op.create_index(op.f('ix_no_object_legacy_survey_matches_object_id'), 'no_object_legacy_survey_matches', ['object_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_no_object_legacy_survey_matches_object_id'), table_name='no_object_legacy_survey_matches')
    op.drop_index(op.f('ix_no_object_legacy_survey_matches_created_at'), table_name='no_object_legacy_survey_matches')
    op.drop_table('no_object_legacy_survey_matches')
    op.drop_index(op.f('ix_no_object_gaia_matches_object_id'), table_name='no_object_gaia_matches')
    op.drop_index(op.f('ix_no_object_gaia_matches_created_at'), table_name='no_object_gaia_matches')
    op.drop_table('no_object_gaia_matches')
    # ### end Alembic commands ###
