"""image_trim_parent_cascade

Revision ID: 04d912266c55
Revises: 57876f7627a2
Create Date: 2026-09-11 16:00:10.064371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d912266c55'
down_revision = '57876f7627a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('image_trim_image_fkey'), 'image_trim_parent', type_='foreignkey')
    op.create_foreign_key('image_trim_image_fkey', 'image_trim_parent', 'images', ['image_id'], ['_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_trim_image_fkey', 'image_trim_parent', type_='foreignkey')
    op.create_foreign_key(op.f('image_trim_image_fkey'), 'image_trim_parent', 'images', ['image_id'], ['_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
