"""image_is_trim

Revision ID: 57876f7627a2
Revises: 01874a39a906
Create Date: 2026-09-10 15:54:39.242869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57876f7627a2'
down_revision = '01874a39a906'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('is_trim', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'is_trim')
    # ### end Alembic commands ###
