"""warped_ref_source_id

Revision ID: 6c992abdd754
Revises: f6577efe80e0
Create Date: 2026-10-09 20:35:50.125320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c992abdd754'
down_revision = 'f6577efe80e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_subtraction_components', sa.Column('warped_ref_source_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_image_subtraction_components_warped_ref_source_id'), 'image_subtraction_components', ['warped_ref_source_id'], unique=False)
    op.create_foreign_key('image_subtraction_warped_sources_fkey', 'image_subtraction_components', 'source_lists', ['warped_ref_source_id'], ['_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_subtraction_warped_sources_fkey', 'image_subtraction_components', type_='foreignkey')
    op.drop_index(op.f('ix_image_subtraction_components_warped_ref_source_id'), table_name='image_subtraction_components')
    op.drop_column('image_subtraction_components', 'warped_ref_source_id')
    # ### end Alembic commands ###
