"""archive_lock

Revision ID: a5d1ea8761c0
Revises: e6cae41b2dec
Create Date: 2026-05-21 13:23:08.381056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d1ea8761c0'
down_revision = 'e6cae41b2dec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_locks',
    sa.Column('serverpath', sa.Text(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_archive_locks__id'), 'archive_locks', ['_id'], unique=False)
    op.create_index(op.f('ix_archive_locks_created_at'), 'archive_locks', ['created_at'], unique=False)
    op.create_index(op.f('ix_archive_locks_serverpath'), 'archive_locks', ['serverpath'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archive_locks_serverpath'), table_name='archive_locks')
    op.drop_index(op.f('ix_archive_locks_created_at'), table_name='archive_locks')
    op.drop_index(op.f('ix_archive_locks__id'), table_name='archive_locks')
    op.drop_table('archive_locks')
    # ### end Alembic commands ###
