apiVersion: v1
stringData:
  flask_secret_key: PUT THE RIGHT THING HERE
  connector_tokens: |
    base/ PUT THE RIGHT THING HERE
kind: Secret
metadata:
  name: file-archive-secrets
  namespace: ls4-production
type: Opaque
