apiVersion: v1
data:
  seechange_dbpasswd: PUT THE RIGHT THING HERE
  flask_secret_key: PUT THE RIGHT THING HERE
  seechange_config.yaml: PUT THE RIGHT THING HERE
kind: Secret
metadata:
  name: webap-secrets
  namespace: ls4-production
type: Opaque
